### PR TITLE
Patch: Switch to jest

### PR DESCRIPTION
**Pull request by ottopecz**
Patch: Switch to jest

### CODE REVIEW

**Review by Trolleymusic — APPROVED** [review]
👍

**Review by pgrzesik — APPROVED** [review]
Looks great 👍

**Review by medikoo — COMMENTED** [review]
We had huge problems with Jest: https://github.com/serverless/serverless/pull/6517

Jest is probably fine for front-end projects, but not for Node.js

**Comment by ottopecz** [comment]
Hi @medikoo ... Thanks so much for the comment you left. I looked through the PR you created for serverless and obviously you researched the problem very thoroughly. All of your points in the comments section were spot on.
In our case though I just wanted to depart from this ancient version of jasmine and to do a cheap and quick migration to a modern "full-service" test framework... so that we can start making changes on the code of the plugin with confidence... Jest is very much inspired by Jasmine so I had to make very little changes as you can see. However in the future we'll definitelly consider to invest the effort and start using Mocha as you guys did with serverless. Thanks again Mate...

**Pull request merged**
