### PR TITLE
fix: Ensure strict schema definitions

### LINKED ISSUE #16: Configuration schema extension does not pass `strict` validation mode
Hello,

along with the upcoming `v3` release of the Serverless Framework, internal schema validation has been improved and now enforces `strict` validation mode. Unfortunately, after preliminary tests, it seems like the schema extension implemented in this plugin does not adhere to strict validation rules and needs to be adjusted in order to support `v3` release of the Framework. The best way to verify that is to use the plugin along with the latest `v3` prerelease (or official release soon). 

I'm happy to answer any additional questions.

### PR DESCRIPTION
**Pull request by pgrzesik**
Closes: https://github.com/Kakkuk/serverless-aws-apigateway-documentation/issues/16

### CODE REVIEW

**Comment by cookieMr** [comment]
Hi all,
@pgrzesik is this PR ready to merge? Is work here done?
Serverless just released 3.0.0 and it seems like this PR would be very helpful.

P.S.
Do you need to update the version in `package.json`?

**Comment by pgrzesik** [comment]
Hey @cookieMr - yes, the PR is ready to merge but I don't have rights. Do you happen to know what is maintaining this repository?

**Comment by cookieMr** [comment]
@pgrzesik 
nope, i am just a happy developer
i have no idea who is maintaining this plugin

**Comment by cookieMr** [comment]
@ottopecz ?

**Comment by Mayhem93** [comment]
Hello guys, until this is merged, the serverless documentation says you can disable the error by using this: `configValidationMode: warn` (https://www.serverless.com/framework/docs/configuration-validation) . Unfortunately it doesn't work :/ has any of you make it work ?

**Comment by cookieMr** [comment]
Someone needs to assume the role of maintainer of this plugin as the `failsafe-engineering` organization seems to have 0 members

i am also waiting for this update, as it blocks us with the update to sls v3

Sad story is that neither swagger nor openapi plugins for sls have any active repo :(

**Comment by Mayhem93** [comment]
I can fork this repo and become a "maintainer" unfortunately I have no ideea on how to write plugins for sls, nor do I have time for that.

If @pgrzesik can help I'm willing to fork it and hand over the role of the maintainer to myself. But I won't be able to do much more than this (eg: actively contributing to the codebase), unless there are minor things which can be easily fixed.

**Comment by pgrzesik** [comment]
I'm afraid I won't be able to help out too much or take over the maintenance of this plugin - I'll report it internally and will come back with potential course of action - thanks @Mayhem93 for expressing interest in helping out

**Comment by pgrzesik** [comment]
Hello @ottopecz - do you think you would be able to merge this one and release a new version? It would be much appreciated 🙇

**Comment by ottopecz** [comment]
@pgrzesik @cookieMr I'll look into to this in the next couple days. Thanks guys for the patience.

**Comment by pgrzesik** [comment]
Thank you @ottopecz - much appreciated 🙇

**Comment by ottopecz** [comment]
This looks like a patch. Do you agree @pgrzesik ?

**Review by ottopecz — APPROVED** [review]

**Comment by cookieMr** [comment]
@ottopecz will you release this into NPM?
https://www.npmjs.com/package/@kakkuk/serverless-aws-apigateway-documentation

**Comment by ottopecz** [comment]
@cookieMr Frigging tests are failing. Looking at it...

**Comment by pgrzesik** [comment]
What exactly is failing @ottopecz? Maybe I can assist with it?

**Pull request merged**
